### ISSUE TITLE
Manual positioning of honeycomb STL has changed

### ISSUE THREAD

**Issue by cchall** [radiasoft/rswarp#21]
Successful comparison to the Meir experiments was carried out with the STLConductor class through 1ff1d6e29ad8a32e87c07f0e0da9b0c06a6fedc2 

Somewhere after this commit a change was made that breaks the positioning of the honeycomb structure. The cause of this needs to be found and understood. It may be a bug or just a poorly understood change that is breaking the current method for centering on a cell of the honeycomb.

**Comment by ncook882** [comment]
Commit 8c57ee5 adds dummy centroid values to the assembly class instantiation.

Commit 9f935f0 introduces scaling attributes for user flexibility and plotting purposes.

I suggest checking out either of these commits to see whether they could be responsible for changing the behavior of the honeycomb grid instantiation.

**Comment by tanxicccc** [comment]
There's no bug in the code, actually, the conductor was installed in an unexpected way. I added a flag to turn on and off the dummy center values, and a side note to remind people to set the scale = 1 as a default. Will commit the changes later.
