### ISSUE TITLE
Bug in serial execution of FieldDiagnostic

### ISSUE THREAD

**Issue by ak782** [radiasoft/rswarp#3]
The FieldDiagnostic does not explicitly require MPI installation in its imports, but in fact breaks down if MPI is not installed. The constructor correctly knows to set self.lparallel = 0 if comm_world is None, but the write() function assumes several times that comm_world != None by checking if self.comm_world.rank == 0. I was able to fix this by replacing every instance of "if self.comm_world.rank == 0" with "if self.lparallel == 0 or self.comm_world.rank == 0" in order to obtain the desired behavior.

**Comment by bruhwiler** [comment]
Is this issue still open?

**Comment by JohanCar1sson** [comment]
This bug is now fixed. Kudos to @ak782 for the perfect bug report!
