### ISSUE TITLE
Ionization products are occasionally emitted with v>c

### ISSUE THREAD

**Issue by JohanCar1sson** [radiasoft/rswarp#8]
@cchall mentioned in the magnetized_cooler_analysis notebook that:
"It is possible for ionization products to be emitted at v>c, this happens only very rarely but does kill the simulation immediately (Warp checks for this). May be due to error in rsoopic module"
I'm opening an issue so I won't forget to try to reproduce this bug.

**Comment by cchall** [comment]
Sorry, this note should have been removed from the example notebook.
This issue should be fixed as of 875f4508dfe1a0f37fbc0bed9c4f1eb76a33823c. It resulted from previous code confusing momentum and velocity getters in Warp. 
I have not seen it happen since this fix.

**Comment by JohanCar1sson** [comment]
Thanks for clarifying @cchall. I have removed mention of this already-fixed bug from the notebook.
